{% set name = "pytradfri" %}
{% set version = "13.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytradfri-{{ version }}.tar.gz
  sha256: c6677b5f2189518a2ed83b5d3aa92dce5fc4cfdbba530904fbebf2c6aee93411

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pydantic

test:
  imports:
    - pytradfri
    - pytradfri.api
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/home-assistant-libs/pytradfri
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: IKEA Trådfri/Tradfri API. Control and observe your lights from Python.
  description: |
    Python package to communicate with the IKEA Trådfri (Tradfri)
    ZigBee Gateway compatible with ZigBee Light Link products. By
    using this library you can communicate with the gateway and
    control IKEA's lights and wall plugs.
  doc_url: https://github.com/home-assistant-libs/pytradfri
  dev_url: https://github.com/home-assistant-libs/pytradfri

extra:
  recipe-maintainers:
    - jan-janssen
