{% set name = "pytradfri" %}
{% set version = "7.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytradfri-{{ version }}.tar.gz
  sha256: f1ea010876de71d8a019ad6965852b6b590f1bd3584d3b0aac3e877c4e47a96b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - pytradfri
    - pytradfri.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/home-assistant-libs/pytradfri
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: IKEA Trådfri/Tradfri API. Control and observe your lights from Python.
  description: |
    Python package to communicate with the IKEA Trådfri (Tradfri)
    ZigBee Gateway compatible with ZigBee Light Link products. By
    using this library you can communicate with the gateway and
    control IKEA's lights and wall plugs.
  doc_url: https://github.com/home-assistant-libs/pytradfri
  dev_url: https://github.com/home-assistant-libs/pytradfri

extra:
  recipe-maintainers:
    - jan-janssen
